export const subscriptionPlans = [
  {
    id: "basic",
    name: "Alus",
    price: 29,
    period: "kuus",
    description: "Täiuslik algus lillede armastajatele",
    features: [
      "1 lillekimp kuus",
      "5–7 tüüpi lilli",
      "Hooajalised lilled",
      "Tasuta kohaletoimetamine",
    ],
    color: "from-pink-900 to-black",
    popular: false,
    image: "https://images.unsplash.com/photo-1490750967868-88df5691cc30?w=400&h=300&fit=crop&auto=format",
  },
  {
    id: "premium",
    name: "Premium",
    price: 59,
    period: "kuus",
    description: "Erilised lilled iga nädal",
    features: [
      "2 lillekimpu kuus",
      "10–12 tüüpi lilli",
      "Eksootilised ja haruldased lilled",
      "Tasuta kohaletoimetamine",
      "Isiklik lillenõustaja",
    ],
    color: "from-pink-800 to-pink-950",
    popular: true,
    image: "https://images.unsplash.com/photo-1519378058457-4c29a0a2efac?w=400&h=300&fit=crop&auto=format",
  },
  {
    id: "luxe",
    name: "Luksus",
    price: 99,
    period: "kuus",
    description: "Parim kogemus lillede maailmas",
    features: [
      "4 lillekimpu kuus",
      "Kõik premium lilled",
      "Käsitsi valitud koosseis",
      "Tasuta kiirkohaletoimetamine",
      "Isiklik lillenõustaja",
      "Eksklusiivsed hooajalised kingitused",
    ],
    color: "from-rose-900 to-black",
    popular: false,
    image: "https://images.unsplash.com/photo-1561181286-d3f5c0c3d157?w=400&h=300&fit=crop&auto=format",
  },
];

export const products = [
  {
    id: "1",
    name: "Roosid punased",
    price: 24.99,
    category: "Roosid",
    description: "Klassikalised punased roosid armastuse väljendamiseks",
    image: "https://images.unsplash.com/photo-XCUqM2TiPFQ?w=800&q=85&auto=format",
    inStock: true,
  },
  {
    id: "2",
    name: "Tulipiid segud",
    price: 19.99,
    category: "Tulipiid",
    description: "Värvilised kevadised tulipiid, mis toovad rõõmu",
    image: "https://images.unsplash.com/photo-M9t2bPAicfM?w=800&q=85&auto=format",
    inStock: true,
  },
  {
    id: "3",
    name: "Peonid roosa",
    price: 29.99,
    category: "Peonid",
    description: "Lopsakad roosad peonid, täis romantilisust",
    image: "https://images.unsplash.com/photo-ZoLqz3VXo4A?w=800&q=85&auto=format",
    inStock: true,
  },
  {
    id: "4",
    name: "Päevalilled",
    price: 17.99,
    category: "Päevalilled",
    description: "Säravad päevalilled, mis toovad suvise tuju",
    image: "https://images.unsplash.com/photo-iEfH3F_W5HU?w=800&q=85&auto=format",
    inStock: true,
  },
  {
    id: "5",
    name: "Orhideed valged",
    price: 39.99,
    category: "Orhideed",
    description: "Elegaantsed valged orhideed luksuslikuks kingituseks",
    image: "https://images.unsplash.com/photo-1584553421349-3557471bed79?w=500&h=400&fit=crop&auto=format",
    inStock: true,
  },
  {
    id: "6",
    name: "Lavendel kimp",
    price: 15.99,
    category: "Lavendel",
    description: "Aroomne lavendelikimp lõõgastumiseks",
    image: "https://images.unsplash.com/photo-1499002238440-d264edd596ec?w=500&h=400&fit=crop&auto=format",
    inStock: false,
  },
  {
    id: "7",
    name: "Hortensiad sinised",
    price: 22.99,
    category: "Hortensiad",
    description: "Uhked sinised hortensiad atmosfääri loomiseks",
    image: "https://images.unsplash.com/photo-1587560699334-cc4ff634909a?w=500&h=400&fit=crop&auto=format",
    inStock: true,
  },
  {
    id: "8",
    name: "Segakimp premium",
    price: 49.99,
    category: "Segakimbud",
    description: "Hoolikalt valitud segakimp kõige erilisematele hetkedele",
    image: "https://images.unsplash.com/photo-1561181286-d3f5c0c3d157?w=500&h=400&fit=crop&auto=format",
    inStock: true,
  },
  {
    id: "9",
    name: "Lilled roosa segakimp",
    price: 34.99,
    category: "Segakimbud",
    description: "Romantiline roosa segakimp armsamale",
    image: "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?w=500&h=400&fit=crop&auto=format",
    inStock: true,
  },
];

export const adminOrders = [
  {
    id: "#FP-1001",
    customer: "Mari Tamm",
    email: "mari.tamm@gmail.com",
    plan: "Premium",
    amount: 59,
    status: "Aktiivne",
    date: "2026-05-15",
    address: "Tartu mnt 12, Tallinn",
  },
  {
    id: "#FP-1002",
    customer: "Jaan Kask",
    email: "jaan.kask@hotmail.com",
    plan: "Alus",
    amount: 29,
    status: "Aktiivne",
    date: "2026-05-18",
    address: "Pärnu mnt 45, Tallinn",
  },
  {
    id: "#FP-1003",
    customer: "Liisa Mägi",
    email: "liisa.magi@mail.ee",
    plan: "Luksus",
    amount: 99,
    status: "Ootel",
    date: "2026-05-20",
    address: "Vabaduse väljak 3, Tallinn",
  },
  {
    id: "#FP-1004",
    customer: "Peeter Saar",
    email: "p.saar@ee.ee",
    plan: "Premium",
    amount: 59,
    status: "Tühistatud",
    date: "2026-05-22",
    address: "Narva mnt 87, Tallinn",
  },
  {
    id: "#FP-1005",
    customer: "Anna Lepp",
    email: "anna.lepp@gmail.com",
    plan: "Alus",
    amount: 29,
    status: "Aktiivne",
    date: "2026-06-01",
    address: "Laagna tee 14, Tallinn",
  },
  {
    id: "#FP-1006",
    customer: "Mats Oja",
    email: "mats.oja@work.com",
    plan: "Luksus",
    amount: 99,
    status: "Aktiivne",
    date: "2026-06-03",
    address: "Kristiine 5, Tallinn",
  },
];
