export const subscriptionPlans = [
  {
    id: "basic",
    name: "Alus",
    price: 29,
    period: "kuus",
    description: "Täiuslik algus lillede armastajatele",
    features: [
      "1 lillekimp kuus",
      "5–7 tüüpi lilli",
      "Hooajalised lilled",
      "Tasuta kohaletoimetamine",
    ],
    color: "from-pink-900 to-black",
    popular: false,
    image: "/images/store.jpg",
  },
  {
    id: "premium",
    name: "Premium",
    price: 59,
    period: "kuus",
    description: "Erilised lilled iga nädal",
    features: [
      "2 lillekimpu kuus",
      "10–12 tüüpi lilli",
      "Eksootilised ja haruldased lilled",
      "Tasuta kohaletoimetamine",
      "Isiklik lillenõustaja",
    ],
    color: "from-pink-800 to-pink-950",
    popular: true,
    image: "/images/about.jpg",
  },
  {
    id: "luxe",
    name: "Luksus",
    price: 99,
    period: "kuus",
    description: "Parim kogemus lillede maailmas",
    features: [
      "4 lillekimpu kuus",
      "Kõik premium lilled",
      "Käsitsi valitud koosseis",
      "Tasuta kiirkohaletoimetamine",
      "Isiklik lillenõustaja",
      "Eksklusiivsed hooajalised kingitused",
    ],
    color: "from-rose-900 to-black",
    popular: false,
    image: "/images/events.jpg",
  },
];

export const adminOrders = [
  {
    id: "#FP-1001",
    customer: "Mari Tamm",
    email: "mari.tamm@gmail.com",
    plan: "Premium",
    amount: 59,
    status: "Aktiivne",
    date: "2026-05-15",
    address: "Tartu mnt 12, Tallinn",
  },
  {
    id: "#FP-1002",
    customer: "Jaan Kask",
    email: "jaan.kask@hotmail.com",
    plan: "Alus",
    amount: 29,
    status: "Aktiivne",
    date: "2026-05-18",
    address: "Pärnu mnt 45, Tallinn",
  },
  {
    id: "#FP-1003",
    customer: "Liisa Mägi",
    email: "liisa.magi@mail.ee",
    plan: "Luksus",
    amount: 99,
    status: "Ootel",
    date: "2026-05-20",
    address: "Vabaduse väljak 3, Tallinn",
  },
  {
    id: "#FP-1004",
    customer: "Peeter Saar",
    email: "p.saar@ee.ee",
    plan: "Premium",
    amount: 59,
    status: "Tühistatud",
    date: "2026-05-22",
    address: "Narva mnt 87, Tallinn",
  },
  {
    id: "#FP-1005",
    customer: "Anna Lepp",
    email: "anna.lepp@gmail.com",
    plan: "Alus",
    amount: 29,
    status: "Aktiivne",
    date: "2026-06-01",
    address: "Laagna tee 14, Tallinn",
  },
  {
    id: "#FP-1006",
    customer: "Mats Oja",
    email: "mats.oja@work.com",
    plan: "Luksus",
    amount: 99,
    status: "Aktiivne",
    date: "2026-06-03",
    address: "Kristiine 5, Tallinn",
  },
];
